# Path in repo: argocd-apps/projects/default-project.yaml
# This is a default project for applications that don't have specific project requirements
# It provides basic permissions for application deployment

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  labels:
    app.kubernetes.io/name: default-project
    app.kubernetes.io/part-of: argocd-apps
spec:
  description: "Default project for applications - provides basic deployment permissions"
  
  # Source repositories allowed for this project
  sourceRepos:
    - "https://github.com/Pagnet/argocd-apps.git"
    - "https://github.com/Pagnet/*.git"  # Allow any repository under your organization
    - "https://blu-helm-charts.blu.com.br/api/charts"  # Your Helm repository
  
  # Destination clusters and namespaces
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  
  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
  
  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: DaemonSet
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
  
  # Roles for this project
  roles:
    - name: developer
      description: "Developer role for application deployment"
      policies:
        - p, proj:default:developer, applications, get, default/*, allow
        - p, proj:default:developer, applications, sync, default/*, allow
        - p, proj:default:developer, applications, action/*, default/*, allow
      groups:
        - developers
    
    - name: admin
      description: "Admin role for project management"
      policies:
        - p, proj:default:admin, applications, *, default/*, allow
        - p, proj:default:admin, applications, action/*, default/*, allow
        - p, proj:default:admin, projects, get, default, allow
        - p, proj:default:admin, repositories, get, *, allow
        - p, proj:default:admin, clusters, get, *, allow
      groups:
        - project-admins
