apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: "Projeto de plataforma (K8s + Crossplane)"
  sourceRepos:
    - https://github.com/Pagnet/argocd-apps
    - https://github.com/Pagnet/crossplane
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
