apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Instance
metadata:
  name: exemplo-ec2
spec:
  forProvider:
    region: us-east-1
    instanceType: t2.micro
    subnetIdSelector:
      matchControllerRef: true  # Vai buscar subnet na mesma stack
    imageId: ami-0c02fb55956c7d316  # Amazon Linux 2 - us-east-1
    keyName: sua-chave-ssh  # (opcional, crie antes na AWS)
    tags:
      - key: Name
        value: exemplo-crossplane
  providerConfigRef:
    name: aws-provider
