# Path in repo: argocd-apps/applications/prod/sample-helm-app.yaml
# Production environment configuration for sample-helm-app
# This is a sample application that demonstrates how to deploy applications using Helm charts
# It shows the integration between ArgoCD and your external Helm repository

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-helm-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: sample-helm-app
    app.kubernetes.io/part-of: sample-apps
    app.kubernetes.io/component: frontend
    environment: production
    app.kubernetes.io/version: production
spec:
  project: production
  source:
    repoURL: https://blu-helm-charts.blu.com.br/api/charts
    targetRevision: "1.0.0"  # Chart version from your Helm repository
    chart: sample-app  # Chart name from your Helm repository
    helm:
      # Helm-specific configuration
      releaseName: sample-app-prod
      # Inline values (can be used instead of or in addition to valueFiles)
      values: |
        image:
          repository: nginx
          tag: "1.25"
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
            - host: sample-app.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: sample-app-prod-tls
              hosts:
                - sample-app.example.com
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        # Production-specific values
        replicaCount: 3
        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
        # Production environment overrides
        environment: production
        debug: false
        logLevel: warn
        # Production security settings
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
  
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-apps-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  revisionHistoryLimit: 15
  
  # Health checks (optional)
  healthChecks:
    - group: apps
      kind: Deployment
      name: sample-app-prod
      namespace: sample-apps-prod
    - group: ""
      kind: Service
      name: sample-app-prod
      namespace: sample-apps-prod
