# =============================================================================
# AWS Provider Deployment Runtime Configuration
# =============================================================================
# This file contains the deployment runtime configuration for the AWS provider
# following security and performance best practices for Crossplane v2.
# =============================================================================

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-controller-config
  labels:
    app.kubernetes.io/name: aws-controller-config
    app.kubernetes.io/component: crossplane-controller
    app.kubernetes.io/part-of: crossplane
    app.kubernetes.io/managed-by: argocd
spec:
  # Deployment template configuration
  deploymentTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: aws-controller-config
        app.kubernetes.io/component: crossplane-controller
        app.kubernetes.io/part-of: crossplane
        app.kubernetes.io/managed-by: argocd
    spec:
      # Basic deployment configuration
      minReadySeconds: 10
      progressDeadlineSeconds: 600
