# =============================================================================
# AWS Provider Configuration - Crossplane v2 Best Practices
# =============================================================================
# This file contains the main AWS provider configuration following current
# industry best practices for Crossplane v2 and GitOps workflows.
#
# Features:
# - Single comprehensive provider for all AWS services
# - Optimized for Crossplane v2.0.2+
# - Compatible with ArgoCD and GitOps workflows
# - Security-first approach with IRSA support
# =============================================================================

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  namespace: crossplane-system
  labels:
    app.kubernetes.io/name: provider-aws
    app.kubernetes.io/component: crossplane-provider
    app.kubernetes.io/part-of: crossplane
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v1.14.0
  packagePullPolicy: IfNotPresent
  ignoreCrossplaneConstraints: false
  deploymentRuntimeConfigRef:
    name: aws-controller-config