# ProviderConfig principal para o provider-aws
# Compatível com Crossplane v2.0.2+
# Usado por TODOS os recursos AWS (EC2, S3, RDS, EKS, IAM, Lambda, 
# Secrets Manager, ElastiCache, Route53, ECR, etc.)
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity
