# Configuração padrão para todos os providers AWS
# Compatível com Crossplane v2.0.2+
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para EC2
# Compatível com Crossplane v2.0.2+
apiVersion: ec2.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: ec2-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para S3
# Compatível com Crossplane v2.0.2+
apiVersion: s3.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: s3-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para RDS
# Compatível com Crossplane v2.0.2+
apiVersion: rds.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: rds-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para EKS
# Compatível com Crossplane v2.0.2+
apiVersion: eks.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: eks-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para IAM
# Compatível com Crossplane v2.0.2+
apiVersion: iam.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: iam-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para Lambda
# Compatível com Crossplane v2.0.2+
apiVersion: lambda.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: lambda-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para Secrets Manager
# Compatível com Crossplane v2.0.2+
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: secretsmanager-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para ElastiCache
# Compatível com Crossplane v2.0.2+
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: elasticache-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para Route53
# Compatível com Crossplane v2.0.2+
apiVersion: route53.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: route53-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity

---
# Configuração específica para ECR
# Compatível com Crossplane v2.0.2+
apiVersion: ecr.aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: ecr-config
spec:
  region: us-east-1
  credentials:
    source: InjectedIdentity
