# =============================================================================
# AWS Provider Configuration - Based on Working Cluster Configuration
# =============================================================================
# This file contains the AWS provider configuration based on the working
# configuration found in the cluster.
# =============================================================================

---
# Primary ProviderConfig using IRSA (Working Configuration)
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
  labels:
    app.kubernetes.io/name: aws-provider-config
    app.kubernetes.io/component: crossplane-provider
    app.kubernetes.io/part-of: crossplane
    app.kubernetes.io/managed-by: argocd
  annotations:
    crossplane.io/description: "Primary AWS ProviderConfig using IRSA"
spec:
  # Use IRSA for secure authentication (working configuration)
  credentials:
    source: InjectedIdentity

