apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-core
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: "*"
    helm:
      releaseName: crossplane
      values: |
        # Environment configs were removed in Crossplane 1.18+
        # Use Composition Functions instead
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
