apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Pagnet/argocd-apps.git
    targetRevision: HEAD
    path: apps/providers
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
