apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Pagnet/crossplane
    targetRevision: main
    path: resources
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true   # enquanto as CRDs sobem
