# apps/infra-crossplane-resources.yaml  (no repo Pagnet/argocd-apps)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"    # depois dos providers
spec:
  project: platform
  source:
    repoURL: https://github.com/Pagnet/crossplane
    targetRevision: main
    path: resources
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
