# =============================================================================
# AWS Resources Examples - Crossplane Provider Usage
# =============================================================================
# This file contains examples of how to use the AWS provider
# to create various AWS resources following best practices.
# =============================================================================

---
# Example 1: S3 Bucket
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-example-bucket
  namespace: default
  labels:
    app.kubernetes.io/name: example-bucket
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: crossplane-examples
spec:
  forProvider:
    region: us-east-1
    versioning:
      enabled: true
  providerConfigRef:
    name: default

---
# Example 2: RDS Instance
# apiVersion: rds.aws.upbound.io/v1beta1
# kind: Instance
# metadata:
#   name: crossplane-example-db
#   namespace: default
#   labels:
#     app.kubernetes.io/name: example-database
#     app.kubernetes.io/component: database
#     app.kubernetes.io/part-of: crossplane-examples
# spec:
#   forProvider:
#     engine: "postgres"
#     engineVersion: "13.7"
#     instanceClass: "db.t3.micro"
#     allocatedStorage: 20
#     storageType: "gp2"
#     storageEncrypted: true
#     backupRetentionPeriod: 7
#     backupWindow: "03:00-04:00"
#     maintenanceWindow: "sun:04:00-sun:05:00"
#     skipFinalSnapshot: true
#     publiclyAccessible: false
#     vpcSecurityGroupIdsRefs:
#       - name: example-db-sg
#     dbSubnetGroupNameRef:
#       name: example-db-subnet-group
#   providerConfigRef:
#     name: default

---
# Example 3: EKS Cluster
# apiVersion: eks.aws.upbound.io/v1beta1
# kind: Cluster
# metadata:
#   name: crossplane-example-cluster
#   namespace: default
#   labels:
#     app.kubernetes.io/name: example-cluster
#     app.kubernetes.io/component: compute
#     app.kubernetes.io/part-of: crossplane-examples
# spec:
#   forProvider:
#     version: "1.28"
#     roleArnRef:
#       name: example-cluster-role
#     vpcConfig:
#       subnetIdsRefs:
#         - name: example-cluster-subnet-1
#         - name: example-cluster-subnet-2
#       securityGroupIdsRefs:
#         - name: example-cluster-sg
#       endpointPrivateAccess: true
#       endpointPublicAccess: true
#       publicAccessCidrs:
#         - "0.0.0.0/0"
#     encryptionConfig:
#       - provider:
#           keyArnRef:
#             name: example-cluster-kms-key
#         resources:
#           - "secrets"
#   providerConfigRef:
#     name: default

---
# Example 4: Lambda Function
# apiVersion: lambda.aws.upbound.io/v1beta1
# kind: Function
# metadata:
#   name: crossplane-example-function
#   namespace: default
#   labels:
#     app.kubernetes.io/name: example-function
#     app.kubernetes.io/component: compute
#     app.kubernetes.io/part-of: crossplane-examples
# spec:
#   forProvider:
#     functionName: "crossplane-example-function"
#     runtime: "python3.9"
#     handler: "index.handler"
#     roleRef:
#       name: example-lambda-role
#     filename: "lambda_function.zip"
#     sourceCodeHash: "base64sha256:example-hash"
#     timeout: 30
#     memorySize: 128
#     environment:
#       variables:
#         ENVIRONMENT: "production"
#   providerConfigRef:
#     name: default

---
# Example 5: Secrets Manager Secret
# apiVersion: secretsmanager.aws.upbound.io/v1beta1
# kind: Secret
# metadata:
#   name: crossplane-example-secret
#   namespace: default
#   labels:
#     app.kubernetes.io/name: example-secret
#     app.kubernetes.io/component: security
#     app.kubernetes.io/part-of: crossplane-examples
# spec:
#   forProvider:
#     name: "crossplane-example-secret"
#     description: "Example secret created by Crossplane"
#     secretString: "{\"username\":\"admin\",\"password\":\"secret123\"}"
#     recoveryWindowInDays: 7
#   providerConfigRef:
#     name: default

---
# Example 6: ElastiCache Cluster
# apiVersion: elasticache.aws.upbound.io/v1beta1
# kind: ReplicationGroup
# metadata:
#   name: crossplane-example-cache
#   namespace: default
#   labels:
#     app.kubernetes.io/name: example-cache
#     app.kubernetes.io/component: cache
#     app.kubernetes.io/part-of: crossplane-examples
# spec:
#   forProvider:
#     replicationGroupId: "crossplane-example-cache"
#     description: "Example Redis cluster created by Crossplane"
#     nodeType: "cache.t3.micro"
#     port: 6379
#     parameterGroupName: "default.redis7"
#     numCacheClusters: 2
#     automaticFailoverEnabled: true
#     multiAzEnabled: true
#     atRestEncryptionEnabled: true
#     transitEncryptionEnabled: true
#     subnetGroupNameRef:
#       name: example-cache-subnet-group
#     securityGroupIdsRefs:
#       - name: example-cache-sg
#   providerConfigRef:
#     name: default
