apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Instance
metadata:
  name: exemplo-ec2
  namespace: crossplane-system
  labels:
    app: exemplo
    environment: test
    managed-by: crossplane
spec:
  forProvider:
    region: us-east-1
    instanceType: t3.micro
    imageId: ami-05a2fdb27f1c1fcc7  # Amazon Linux 2 AMI in us-east-1
    securityGroupIds:
      - sg-09f6b39b646df3bb7  # Replace with your security group
    subnetId: subnet-01543f0c2f9c8d7c4  # Replace with your subnet
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 8
          volumeType: gp3
          deleteOnTermination: true
          encrypted: true
    userData: |
      #!/bin/bash
      yum update -y
      yum install -y httpd
      systemctl start httpd
      systemctl enable httpd
      echo "<h1>Hello from Crossplane-managed EC2 instance!</h1>" > /var/www/html/index.html
    tags:
      - key: Name
        value: exemplo-ec2-test
      - key: Environment
        value: test
      - key: Service
        value: exemplo
      - key: ManagedBy
        value: crossplane
