apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: minha-ec2
  namespace: crossplane-system
  labels:
    app: minha-ec2
    environment: test
    managed-by: crossplane
    argocd.argoproj.io/instance: minha-ec2
spec:
  forProvider:
    region: us-east-1
    instanceType: t3.micro
    imageId: ami-0c02fb55956c7d316  # Amazon Linux 2 AMI in us-east-1
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 8
          volumeType: gp3
          deleteOnTermination: true
          encrypted: true
    userData: IyEvYmluL2Jhc2gKeXVtIHVwZGF0ZSAteQp5dW0gaW5zdGFsbCAteSBodHRwZApzeXN0ZW1jdGwgc3RhcnQgaHR0cGQKc3lzdGVtY3RsIGVuYWJsZSBodHRwZAplY2hvICI8aDE+SGVsbG8gZnJvbSBBcmdvQ0QtbWFuYWdlZCBFQzIgaW5zdGFuY2UhPC9oMT4iID4gL3Zhci93d3cvaHRtbC9pbmRleC5odG1s
    tags:
      - key: Name
        value: minha-ec2-test
      - key: Environment
        value: test
      - key: Service
        value: minha-ec2
      - key: ManagedBy
        value: crossplane
  providerConfigRef:
    name: aws-provider-config
