apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Instance
metadata:
  name: exemplo-ec2
spec:
  forProvider:
    region: us-east-1
    instanceType: t3.micro
    subnetId: subnet-01543f0c2f9c8d7c4
    imageId: ami-0c02fb55956c7d316
    tags:
      - key: Name
        value: exemplo-crossplane
  providerConfigRef:
    name: aws-provider-config
