apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: minha-ec2
  namespace: crossplane-system
  labels:
    app: minha-ec2
    environment: test
    managed-by: crossplane
spec:
  forProvider:
    region: us-east-1
    instanceType: t3.micro
    ami: ami-0c02fb55956c7d316  # ✅ CORRECT
    rootBlockDevice:            # ✅ CORRECT
      - volumeSize: 8
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
    vpcSecurityGroupIds:        # ✅ CORRECT
      - sg-0123456789abcdef0
    userData: |
      #!/bin/bash
      yum update -y
      yum install -y httpd
      systemctl start httpd
      systemctl enable httpd
      echo "<h1>Hello from ArgoCD-managed EC2 instance!</h1>" > /var/www/html/index.html
    tags:                       # ✅ CORRECT
      Name: minha-ec2-test
      Environment: test
      Service: minha-ec2
      ManagedBy: crossplane
  providerConfigRef:
    name: aws-provider-config
